#!/bin/sh

status=$(connmanctl technologies | grep -oE "Connected = True")
essid=$(nmcli -t -f active,ssid dev wifi | grep '^yes' | cut -d: -f2)

if [ $status ] ; then
    icon=" "
    text="Connected"
    col="#a1bdce"
else
    icon="睊"
    text="Disconnected"
    col="#575268"
fi


case $1 in
	--COL) echo $col;;
	--ESSID) echo $text;;
	--ICON) echo $icon;;
esac

