preload = $HOME/Pictures/Wallpaper/anime_wallpaper2.png
preload = $HOME/Pictures/Wallpaper/cool_wallpaper.png.png

wallpaper = HDMI-A-1, $HOME/Pictures/Wallpaper/anime_wallpaper2.png
wallpaper = eDP-1, $HOME/Pictures/Wallpaper/anime_wallpaper2.png

