# preload = $HOME/Pictures/Wallpaper/anime_wallpaper2.png
# preload = $HOME/Pictures/Wallpaper/cool_wallpaper.png
# preload = $HOME/Pictures/Wallpaper/anime_wallpaper.png
# preload = $HOME/Pictures/Wallpaper/smile.jpg
# preload = $HOME/Pictures/Wallpaper/old.png
# preload = $HOME/Pictures/Wallpaper/cyber.jpg
preload = $HOME/Pictures/Wallpaper/dark.png

wallpaper = , $HOME/Pictures/Wallpaper/dark.png
# splash = true
