# preload = $HOME/Pictures/Wallpaper/anime_wallpaper2.png
# preload = $HOME/Pictures/Wallpaper/cool_wallpaper.png
# preload = $HOME/Pictures/Wallpaper/anime_wallpaper.png
preload = $HOME/Pictures/Wallpaper/smile.jpg
preload = $HOME/Pictures/Wallpaper/cyber.jpg

# wallpaper = , $HOME/Pictures/Wallpaper/anime_wallpaper.png
wallpaper = , $HOME/Pictures/Wallpaper/smile.jpg
splash = true
