# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi


# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
# If you come from bash you might have to change your $PATH.

#ZSH_THEME="robbyrussell"
ZSH_THEME="minimal" # set by `omz`


#. /home/synerr/.cache/wal/colors.sh
#ZSH_THEME="macos-zsh-theme/macos-theme"


# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment one of the following lines to change the auto-update behavior
# zstyle ':omz:update' mode disabled  # disable automatic updates
# zstyle ':omz:update' mode auto      # update automatically without asking
zstyle ':omz:update' mode reminder  # just remind me to update when it's time

plugins=(colored-man-pages colorize command-not-found copybuffer copyfile encode64 extract sudo themes z zsh-autosuggestions zsh-syntax-highlighting)

COMPLETION_WAITING_DOTS="true"


function n ()
{
    # Block nesting of nnn in subshells
    if [[ "${NNNLVL:-0}" -ge 1 ]]; then
        echo "nnn is already running"
        return
    fi

    export NNN_TMPFILE="${XDG_CONFIG_HOME:-$HOME/.config}/nnn/.lastd"

    # Unmask ^Q (, ^V etc.) (if required, see `stty -a`) to Quit nnn
    # stty start undef
    # stty stop undef
    # stty lwrap undef
    # stty lnext undef

    # The backslash allows one to alias n to nnn if desired without making an
    # infinitely recursive alias
    /usr/bin/nnn "$@"

    if [ -f "$NNN_TMPFILE" ]; then
            . "$NNN_TMPFILE"
            rm -f "$NNN_TMPFILE" > /dev/null
    fi
}

function gdbpid ()
{
    #pidof $1 | xargs -I{} echo {}
	pidof $1 | xargs -I{} gdb --pid {} -c "b main"
}

function disablemon()
{
    sudo ifconfig wlan0 down
    sudo iwconfig wlan0 mode Managed
    sudo ifconfig wlan0 up
    sudo systemctl restart connman
}


#
#function nnn_cd()
#{
#    if ! [ -z "$NNN_PIPE" ]; then
#        printf "%s\0" "0c${PWD}" > "${NNN_PIPE}" !&
#    fi
#}
#
#trap nnn_cd EXIT
#
# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
#


export ZSH="$HOME/.oh-my-zsh"
source $ZSH/oh-my-zsh.sh

. /home/synerr/.zsh/aliases.zsh
. /home/synerr/.zsh/exports.zsh
. /home/synerr/.zsh/docker_funcs.zsh

[[ ! -f ~/.zsh/.p10k.zsh ]] || source ~/.zsh/.p10k.zsh
. "/home/synerr/.acme.sh/acme.sh.env"
