#!/usr/bin/env bash
hyprctl dispatch focusmonitor 0
eww -c $HOME/.config/hypr/themes/adventure/eww/bar open bar --toggle --screen 0

NB_MONITORS=$(hyprctl monitors -j | jq length)
if [ "$NB_MONITORS" -eq "2" ]; then
    hyprctl dispatch focusmonitor 1
    eww -c ~/.config/hypr/themes/adventure/eww/bar open bar-external --toggle --screen 1
fi
