# Shell variables
# Generated by 'wal'
wallpaper='/home/synerr/Pictures/Wallpaper/wallpaper_leaf.jpg'

# Special
background='#090B14'
foreground='#bedfd5'
cursor='#bedfd5'

# Colors
color0='#090B14'
color1='#224D4E'
color2='#19526A'
color3='#1D9468'
color4='#196392'
color5='#4E588F'
color6='#42ABA8'
color7='#bedfd5'
color8='#859c95'
color9='#224D4E'
color10='#19526A'
color11='#1D9468'
color12='#196392'
color13='#4E588F'
color14='#42ABA8'
color15='#bedfd5'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
