--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/synerr/Pictures/Wallpaper/wallpaper_leaf.jpg"

-- Special
background="#090B14"
foreground="#bedfd5"
cursor="#bedfd5"

-- Colors
color0="#090B14"
color1="#224D4E"
color2="#19526A"
color3="#1D9468"
color4="#196392"
color5="#4E588F"
color6="#42ABA8"
color7="#bedfd5"
color8="#859c95"
color9="#224D4E"
color10="#19526A"
color11="#1D9468"
color12="#196392"
color13="#4E588F"
color14="#42ABA8"
color15="#bedfd5"
