foreground   #bedfd5
background   #090B14
cursor       #bedfd5

color0       #090B14
color8       #859c95
color1       #224D4E
color9       #224D4E
color2       #19526A
color10      #19526A
color3       #1D9468
color11      #1D9468
color4       #196392
color12      #196392
color5       #4E588F
color13      #4E588F
color6       #42ABA8
color14      #42ABA8
color7       #bedfd5
color15      #bedfd5
