#Commands to be executed at launch
exec-once = dunst
exec-once = waybar

exec-once=dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP GDK_BACKEND
exec-once=blueman-applet # Make sure you have installed blueman + blueman-utils
exec-once=wl-clipboard-history -t
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec-once=wlsunset -S 9:00 -s 19:00 -t 4000 -T 5000 
exec=pkill -9 flicker
exec-once=killall hypridle; hypridle
exec-once=openrgb --server

# XDG-DESKTOP-PORTAL NIGGER
exec-once=~/.config/hypr/scripts/xdph

exec-once=avizo-service
# exec-once=hyprpaper
exec-once=swww-daemon
exec-once = hyprctl setcursor Bibata-Modern-Classic 22
exec-once = wl-paste --watch cliphist store &
exec-once = hyprpm reload
exec-once=keepassxc
exec-once=eval $(ssh-agent)
exec-once=thunderbird
