[shell]
program="/usr/bin/zsh"

[window]
dynamic_padding=true
opacity=0.9
[window.padding]
x=10
y=5

[font]
size=13

[font.normal]
family = "Fira Code"
style = "Regular"

[font.bold]
family = "Fira Code"
style = "Bold"

[font.italic]
family = "Fira Code"
style = "Italic"

[font.bold_italic]
family = "Fira Code"
style = "Bold Italic"

[font.offset]
x = 0
y = 0

[cursor]
style="Underline"

