import = [
  "~/.config/alacritty/themes/themes/dracula.toml"
]

[keyboard]
bindings = [
  { key = "Return", mods = "Super", action = "SpawnNewInstance" },
  { key = "N",   mods = "Control|Shift", action = "SpawnNewInstance" }
]

[cursor]
style="Block"


[shell]
program="/usr/bin/fish"

[scrolling]
history=20000

[window]
dynamic_padding=true
opacity=0.9
padding = {x = 10, y = 5}
decorations = "Full"
blur = true
decorations_theme_variant = "Dark"

[font]
size=13
offset = {x = 0, y = 0}

[font.normal]
family = "Fura Code Nerd Font"
style = "Regular"

[font.bold]
family = "Fura Code Nerd Font"
style = "Bold"

[font.italic]
family = "SpaceMono Nerd Font"
style = "Italic"

[font.bold_italic]
family = "SpaceMono Nerd Font"
style = "Bold Italic"
